### ISSUE TITLE
Add ability to load settings from the folder

### ISSUE THREAD

**Issue by miry** [bigbinary/handy#5]
Currently we load only one file. It is not comfort when we deploy to servers and there are not some envs. So I suggest next common solutions:

Load files from the `config/settings` depends on current rails env. same logic like do rails for environments. Example: file `config/settings/production.yml` would be loaded in production env.

@neerajdotname what do you think?

**Comment by prathamesh-sonpatki** [comment]
We are moving away from loading settings from `settings.yml` in newer apps because of using  `Rails.application.secrets` and `.rbenv-vars`. Closing this issue.
